name: deploy
on:
    push:
        branches:
            - main
jobs:
    deploy-dns:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ./scripts/verify.sh
            - uses: erlef/setup-beam@v1
              with:
                  otp-version: "27.1.2"
                  gleam-version: "1.6.0"
                  rebar3-version: "3"
            - run: gleam deps download
            - run: gleam run
              env:
                  PORKBUN_SECRET_KEY: ${{ secrets.PORKBUN_SECRET_KEY }}
                  PORKBUN_API_KEY: ${{ secrets.PORKBUN_API_KEY }}
