name: verify
on:
    push:
        branches:
            - main
    pull_request:
jobs:
    verify-domains:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ./scripts/verify.sh
